# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: ~/plugins/vortechron/point/models/customer/columns.yaml

# Model Class name
modelClass: Vortechron\Point\Models\Customer

# List Title
title: Customers List

# Link URL for each record
recordUrl: vortechron/point/customers/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 5

# Display checkboxes next to each record
showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt



